database:
  type: sqlite
  rebuild: True
  dataset_path: datasets/data_wiki_cleaned
  database_path: qatask/database/wikipedia_db/wikisqlite.db # Path to the database file
  preprocess: qatask/preprocess/wiki_preprocess.py
  num_workers: 32
reader: 
  type: default
retriever:
  rebuild: True
  type: tf-idf
  top_k: 5
  ngram: 2
  hash_size: 28 #to power of 28
  db_path: qatask/database/wikipedia_db/wikisqlite.db
  num_workers: 32
  checkpoint: checkpoint/TFIDF_models/
postprocessor: 
  type: default
pipeline:
  type: default
tokenizer:
  type: vnm
