database:
  type: sqlite
  rebuild: False
  dataset_path: datasets/wikicorpus
  database_path: qatask/database/wikipedia_db/wikisqlite.db # Path to the database file
  preprocess: qatask/preprocess/dummy.py
  num_workers: 32
reader: 
  type: bert_xlm
  threshold: 0.00000000000000000001
  weighted_mu: 0.5
  model_checkpoint: nguyenvulebinh/vi-mrc-large
  batch_size: 100 # can up to 600 on RTX 3090 
  logpth: "logs/"
retriever:
  type: dual_bm25
  top_passage: 13
  top_title: 3
  index_path: checkpoint/indexes/BM25
  index_path_title: checkpoint/indexes/BM25_post
  db_path_title: qatask/database/wikipedia_db/wikisqlite_post.db 
postprocessor:
  type: bm25
  top_k: 200
  # database_path: qatask/database/wikipedia_db/wikisqlite_final1.db # Might have to change to original db wikisqlite.db since the new one seems to produce many duplicated pages
  database_path: qatask/database/wikipedia_db/wikisqlite_post.db 
  index_path: checkpoint/indexes/BM25_post
pipeline:
  type: default
tokenizer:
  type: vnm
