database:
  type: sqlite
  rebuild: False
  dataset_path: datasets/wikicorpus
  database_path: qatask/database/wikipedia_db/wikisqlite.db # Path to the database file
  preprocess: qatask/preprocess/dummy.py
  num_workers: 32
reader: 
  type: bert_xlm
  threshold: 0.00000000000000000001
  weighted_mu: 0.5
  model_checkpoint: nguyenvulebinh/vi-mrc-large
  batch_size: 100 # can up to 600 on RTX 3090 
  logpth: "logs/"
retriever:
  type: hybrid
  top_k: 5
  top_h: 30
  index_path: checkpoint/indexes/BM25
  passage_encoder: checkpoint/dpr_zalo_v1/passage_encoder
  query_encoder: checkpoint/dpr_zalo_v1/query_encoder
postprocessor: 
  type: bm25
  top_k: 100
  # database_path: qatask/database/wikipedia_db/wikisqlite_final1.db # Might have to change to original db wikisqlite.db since the new one seems to produce many duplicated pages
  database_path: qatask/database/wikipedia_db/wikisqlite_post.db 
  index_path: checkpoint/indexes/BM25_post
pipeline:
  type: default
tokenizer:
  type: vnm
